fix ``` Compilation error in .../diag-upload-service/diag-upload-api/src/server.ts [ERROR] Unable to compile TypeScript: error TS5109: Option 'moduleResolution' must be set to 'NodeNext' (or left unspecified) when  option 'module' is set to 'NodeNext'. ```